### ISSUE TITLE
WTForm's CSRF token is unusable in the context of multiple app invocations

### ISSUE THREAD

**Issue by daniel-j-h** [spz-signup/spz-signup#21]
WTForm's CSRF token is unusable in a multithreaded (or multiple app instances) environment. We have to disable it for deployment.

What to do about it? There's no easy solution, as the only centralized state is the database, so we would have to, kind of, wrap the mechanism.

**Comment by crepererum** [comment]
The central mutual state is not required when we use an HMAC+secret+rng. `itsdangerous` already implements the required tools and WTForms supports implementing our own token generator+checker as of http://wtforms.readthedocs.org/en/latest/csrf.html#creating-your-own-csrf-implementation . The following things are left to check:

 1. Is this really secure?
 2. Do we have enough random state on the server side? (We already use quite a good amount for TLS) If not, should we harvest more?

**Comment by daniel-j-h** [comment]
Prior art: [token.py](https://github.com/spz-signup/spz-signup/blob/39cc0fed090a0e74eddf119973eb82acfe05ab39/spz/token.py) for generating and validating the one-time-tokens for pre-term signups. Take a look at how it's done there (really easy to pull off).

I wouldn't think about entropy sources for now, all this is supposed to do is to prevent CSRFs.

**Comment by crepererum** [comment]
Yes, I'm aware that we already use this. And you are actually following the described HMAC procedure (without knowing it? :wink:).

A word on the entropy: The CSFR token is, in contrast to the mail token, used under heavy load. When the entropy source gets sucked out, all processes (including TLS requests) stall.

**Comment by daniel-j-h** [comment]
Have to see the amount of requests hammering that system before stalling TLS requests :) but could be --- at least keep it in mind and as always: check, profile, validate, benchmark!

Eh, the token hint was exactly because you want to do something similar. I think we also talked about the HMAC design for the one-time-tokens last year during a run.

**Comment by crepererum** [comment]
:+1:
