### ISSUE TITLE
Avoid specification of "Sex/Gender"

### ISSUE THREAD

**Issue by crepererum** [spz-signup/spz-signup#32]
# Problem Description
The "Sex" attribute isn't required for processing a user registration, but it's problematic because there exist people without a clear female or male gender. This can have many reasons, e.g. genetic, hormonal or psychological ones. This unneeded information only leads to discrimination. See the Wikipedia article ([en](https://en.wikipedia.org/wiki/Third_gender), [de](https://de.wikipedia.org/wiki/Drittes_Geschlecht)) for more details.

Another point is that if you know this information, a lawsuit can be filed because it might be possible that you prefer a gender during the processing of the registrations. Even though it's clear for me and most people out there that this is definitely not the case, some frustrated person can come up with this idea.

# Solution
Remove the "sex/gender" attribute.

# Alternative Solution
Introduce a third "other"(en)/"andere"(de) choice. Although the primary solution should be preferred because the wording "other"/"andere"/anders" is negatively biased.

# Other effects
The wording "Herr/Frau" on the certificates should be removed or not specified (right now they tend to cross one of the titles).

**Comment by daniel-j-h** [comment]
I'm sorry, but management does not want us to implement this. Thanks for your feedback.

**Comment by crepererum** [comment]
To be fixed for WS16/17

**Comment by crepererum** [comment]
Closed by c767eac92d6e441130daa8ade2eb2cf3f0bcd1f7
