### ISSUE TITLE
Edge case 0 days 0 hours 0 minutes

### ISSUE THREAD

**Issue by crepererum** [spz-signup/spz-signup#33]
# Problem
If you try to sign up before the official registration window starts, you get an error saying that you have to wait "DD days HH hours MM minutes". But if there are less than 60 seconds (but more than 0) left it tells the user to wait "00 days 00 hours 00 minutes" which is equal to zero. This leads to the confusing situation that you have to wait but the remaining time isn't really specified.

# Solution
There are 4 possible solutions:
 1. Always add the number of seconds, so the user sees "DD days HH hours MM minutes SS seconds"
 2. Only add the number of seconds if the remaining time is less than 60 seconds. In this edge case it would be "SS seconds"
 3. Use a unspecific message for the described case like "some seconds"
 4. Always round up the number of minutes.

# Discussion
The solutions are ordered by exactness (therefore value for the users) starting with solution 1. as the most exact information going down to solution 4. as the least informative message. To help the users solution 1. should be implemented. The only drawback is that there can be a delay of some seconds until the page is shown to the user (due to network and render latency) so the number of seconds isn't that exact. But still this is better than the other variants.

**Comment by daniel-j-h** [comment]
Was fixed in https://github.com/spz-signup/spz-signup/commit/e5bed7f8861f3d2002a4468625c99fbc5842a19f

But it seems like we have to switch from a time-based first-come-first-served scheme anyways.
