### ISSUE TITLE
Prioritize system's mails over signup mails

### ISSUE THREAD

**Issue by daniel-j-h** [spz-signup/spz-signup#41]
Mail sending is done asynchronously using rq. But there is no prioritization going on; that is, if there are 5k mails in the queue we still want system's mails (e.g. token and status change mails) to be delivered as fast as possible.

rq supports this -- implement this!

**Comment by crepererum** [comment]
Implemented, in a way I think it makes sense. There are 2 queues now (normal, which should not be used for bulk-sending) and slow_mails (which handles all the bulk-send operations). The queues are rate-limited per worker (and there is one worker per queue), so you can bypass the slow queue by using the normal one.
