### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by crepererum** [spz-signup/spz-signup#45]
## Abstract
Let's move to a shiny new version of Python to get rid of some old leftovers.

## Why
 - better Unicode handling, by default (`u'whatever'` => `'whatever'`)
 - no `wsgiref` backport
 - all type of list/dict comprehensions (possible now, but let's do this while moving over)
 - iterators by default (don't worry about accidentally allocating too much memory)
 - someday (not now!) we could introduce coroutines plus async
 - future maintainers (someday, I need to find another maintainer. Python 2 is old and not really "laser" anymore.)

## The work
Migration is simple on the code side, see [`python/3.4` branch](https://github.com/spz-signup/spz-signup/tree/python/3.4) (no Python 3.5 for now, because we are waiting for some dependencies to get their homework done). On the server side, we need to upgrade the OS anyway someday. Maybe we are going to move over to Docker, which would simplify a lot. As a fall-back, we can just install an up-to-date Python version from a 3rd-party repo.

My coworkers: I'll explain everything. All changes, all implications, all new stuff. And I am here to help and answer questions. As you can see in the example branch, the changes are quite minimal and even simplify the code in many places.

**Comment by crepererum** [comment]
CC @daniel-j-h for comments and suggestions on that one.

**Comment by daniel-j-h** [comment]
The last time I checked only the PDF generation package wasn't working with Python3 (and maybe we can do that client-side anyway, or use a different library).

Please check with the infrastructure team re. operating system you get on the VM, I think it's Debian oldstable (i.e. not Jessie).
