### ISSUE TITLE
Course overview: show more information

### ISSUE THREAD

**Issue by crepererum** [spz-signup/spz-signup#46]
Implement something that shows more information about the courses, especially the data we got from the provided JSON files. This should help to review the information in a human-readable and understandable form, because the JSON data seems to contain some ugly copy+paste errors (e.g. wrong test point ranges for English courses, wrong registration time windows).

**Comment by daniel-j-h** [comment]
Yeah, sounds reasonable --- in the best case you do it similarly to the pre-term token technique: let users provide the data themselves. So maybe an interface that lets management put in courses (but not for direct use in the system, but to add them to a 'staging area').

**Comment by crepererum** [comment]
The editing part won't be realized during the winter. That's quite an amount of work to build an interface that is fast, easy understandable and powerful.
