### ISSUE TITLE
Move away from Persona

### ISSUE THREAD

**Issue by daniel-j-h** [spz-signup/spz-signup#51]
Persona is dead (unfortunately), better move away from it until it is too late and things will break.

http://www.stavros.io/posts/open-letter-mozilla-bring-back-persona/

**Comment by crepererum** [comment]
Will evaluate to either support OpenID or to just use a simple Username+PW (generated). We'll need to adjust the role system anyway, because we need to split the `restricted` part into language-specific roles.
