### ISSUE TITLE
DDoS prevention

### ISSUE THREAD

**Issue by crepererum** [spz-signup/spz-signup#52]
Requirements:
 - low overhead (especially: fast storage ops)
 - ideally measure used resources instead of pure request amount
   - idea: multiple request with a factor (e.g. internal has a higher factor, failed requests an even higher)
 - multiple stages:
   - warning first
   - minimal self-contained error page second
   - not-accepting TCP opens last
 - no client state

**Comment by daniel-j-h** [comment]
Hint: Redis is already running for the `rq` queuing system; and/or do it on the Nginx level.
