### ISSUE TITLE
Is the idx_prepare implementation correct?

### ISSUE THREAD

**Issue by daniel-j-h** [spz-signup/spz-signup#59]
I just wanted to look something Python / Flask related up and stumbled upon

https://github.com/spz-signup/spz-signup/blob/e86cf383c4b0ce4d29034ea12c971561392053e2/images/spz/spz/populate.py#L138-L145

which looks like it could produce a div-by-zero.

To be specific `1 / max(1, len(attendances))` can only possibly be evaluated to `1 / 1` or `1 / 0`.

Can you take a quick look please, as I'm not into the code to precisely follow what's going on here.

**Comment by crepererum** [comment]
Nope. 
Maximum of 1 and another number is always at least 1. So the result is between 0 (excluding) and 1 (including). 
And the max is only a security measure because there are only people considered at this point who have an attendance relation. And it's called after the filter.

**Comment by daniel-j-h** [comment]
Oh man I need some coffee
